Ignore dependent types
awsweeper detects dependent types and lists them in the yaml output, but
when one tries to delete them it reports:

    Error: invalid filter: unsupported resource type: aws_iam_user_policy

when they are not included but related users are being deleted it
auto-injects them again. To avoid the failure introduce a
dependent_types set to ignore them in awscleaner (they will be deleted
by awsweeper based on the relevant resource).

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>